# Generated by Django 3.0.3 on 2020-03-02 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_contents',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
